### ISSUE TITLE
Substructure markings carrying over to next molecule

### ISSUE THREAD

**Issue by clintonjules** [swamidasslab/xenopict#2]
If a molecule as xenopict object is marked before another one is made, then the marking from the previous molecule xenopict object appears on the following one. In the second image, it is depicted by the darker circles.

```
from xenopict import Xenopict, magic

mol = 'CCCC(=O)OC(CNC(C)(C)C)COc1nsnc1N1CCOCC1'
sub = "nsncOCCO"
idx = [18, 17, 16, 15, 14, 13, 6, 5]
idx_new = [17, 16, 15, 19, 20, 21, 22, 23, 24, 25]

svg1 = Xenopict(mol)
svg1.mark_atoms(idx)
svg1.halo()

svg2 = Xenopict(mol)
svg2.mark_atoms(idx_new)
svg2.halo()

svg1, svg2
```

<img width="309" alt="mol1" src="https://user-images.githubusercontent.com/13054455/192388458-0aa17353-5702-4bc1-9cee-944bffcb87b5.png">
<img width="309" alt="mol2" src="https://user-images.githubusercontent.com/13054455/192388459-41b9f982-25eb-4565-996f-67974a239c5c.png">

**Comment by swamidass** [comment]
This is now fixed in current version. We added unique tag to all ID and HREF attributes on svg export.
